-- 0161 — crm_leads.external_id vira chave de idempotência de verdade.
--
-- A coluna já existia (para leads que nascem em outro sistema — import, CRM
-- externo, o prospector de sites), mas sem UNIQUE nada impedia um upsert
-- rodado duas vezes de criar dois leads para o mesmo `external_id`. É
-- exatamente o padrão que a doutrina do repo já usa para mensagem/evento
-- externo (`unique (organization_id, external_id)` + captura de 23505) — só
-- que aqui faltava aplicado a `crm_leads`.
--
-- Índice COMPLETO, não parcial: um índice `where external_id is not null`
-- pareceria mais barato (a maioria dos leads não tem external_id), mas
-- PostgREST infere o alvo do `ON CONFLICT` a partir de `on_conflict=col,col`
-- só quando existe um índice único SEM predicado — um parcial exige
-- `ON CONFLICT (...) WHERE ...` explícito, que o upsert do PostgREST não
-- gera. Sem isso, todo upsert feito pela REST (o caminho que o script do
-- prospector de sites usa) cairia com "there is no unique or exclusion
-- constraint matching the ON CONFLICT specification". O índice completo
-- não perde nada: NULL nunca colide com NULL num UNIQUE comum, então lead
-- criado à mão (sem `external_id`) continua livre para existir em qualquer
-- quantidade.
create unique index if not exists "crm_leads_org_external_id_key"
  on "public"."crm_leads" ("organization_id", "external_id");
